name: Publish ClickOnce

on:
  push:
    tags:
      - "*.*.*"  # Runs only when a new version tag is pushed

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Version from Tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update AssemblyInfo.cs with Version
        run: |
          $assemblyInfoPath = "app/Properties/AssemblyInfo.cs"
          (Get-Content $assemblyInfoPath) -replace '\[assembly: AssemblyVersion\(".*"\)\]', "[assembly: AssemblyVersion(`"${{ env.VERSION }}`")]"
          | Set-Content $assemblyInfoPath
        shell: pwsh

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet Packages
        run: nuget restore GopsDailySheet.sln

      - name: Build and Publish ClickOnce
        run: msbuild /target:Publish /p:Configuration=Release /p:PublishDir="publish/" 

      - name: Create a zip file
        run: |
          mkdir publish
          Compress-Archive -Path app\publish\* -DestinationPath publish\release.zip

      - name: Create latest.json
        run: |
          echo '{' > publish/latest.json
          echo '  "version": "${{ env.VERSION }}",' >> publish/latest.json
          echo '  "download_url": "https://github.com/brunotag/gopsdailysheet/releases/latest/download/v${{ env.VERSION }}/release.zip"' >> publish/latest.json
          echo '}' >> publish/latest.json

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            publish/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
